// <auto-generated />

using BlogConsole.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using System;

namespace BlogConsole.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Title");

                b.Property<string>("Url");

                b.HasKey("Id");

                b.ToTable("Blogs");
            });

            modelBuilder.Entity("Comment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Content");

                b.Property<int>("PostId");

                b.Property<string>("Title");

                b.HasKey("Id");

                b.HasIndex("PostId");

                b.ToTable("Comments");
            });

            modelBuilder.Entity("Microsoft.EntityFrameworkCore.AutoHistory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Changed")
                    .HasMaxLength(2048);

                b.Property<DateTime>("Created");

                b.Property<int>("Kind");

                b.Property<string>("RowId")
                    .IsRequired()
                    .HasMaxLength(50);

                b.Property<string>("TableName")
                    .IsRequired()
                    .HasMaxLength(128);

                b.HasKey("Id");

                b.ToTable("AutoHistory");
            });

            modelBuilder.Entity("Post", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("BlogId");

                b.Property<string>("Content");

                b.Property<string>("Title");

                b.HasKey("Id");

                b.HasIndex("BlogId");

                b.ToTable("Posts");
            });

            modelBuilder.Entity("Comment", b =>
            {
                b.HasOne("Post", "Post")
                    .WithMany("Comments")
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("Post", b =>
            {
                b.HasOne("Blog", "Blog")
                    .WithMany("Posts")
                    .HasForeignKey("BlogId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}